In [2]:
import pandas as pd

Load the Facebook data and show the header

In [13]:
df = pd.read_csv('FB_data.csv')
df.count()
df.head()

,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,2018-03-27,156.31,162.85,150.75,152.19,76787884.0,0.0,1.0,156.31,162.85,150.75,152.19,76787884.0
1,2018-03-26,160.82,161.10,149.02,160.06,125438294.0,0.0,1.0,160.82,161.10,149.02,160.06,125438294.0
2,2018-03-23,165.44,167.10,159.02,159.39,52306891.0,0.0,1.0,165.44,167.10,159.02,159.39,52306891.0
3,2018-03-22,166.13,170.27,163.72,164.89,73389988.0,0.0,1.0,166.13,170.27,163.72,164.89,73389988.0
4,2018-03-21,164.80,173.40,163.30,169.39,105350867.0,0.0,1.0,164.80,173.40,163.30,169.39,105350867.0

Show count

In [8]:
df.count()

Date           1472
Open           1472
High           1472
Low            1472
Close          1472
Volume         1472
Ex-Dividend    1472
Split Ratio    1472
Adj. Open      1472
Adj. High      1472
Adj. Low       1472
Adj. Close     1472
Adj. Volume    1472
dtype: int64

In [28]:
#df.set_index('Date',inplace=True)
#df.groupby(['Date','Volume']).max()
df.groupby(['Date','Volume']).max()

,,Open,High,Low,Close,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,Volume,,,,,,,,,,,
2012-05-18,573576400.0,42.050,45.0000,38.0000,38.2318,0.0,1.0,42.050,45.0000,38.0000,38.2318,573576400.0
2012-05-21,168192700.0,36.530,36.6600,33.0000,34.0300,0.0,1.0,36.530,36.6600,33.0000,34.0300,168192700.0
2012-05-22,101786600.0,32.610,33.5900,30.9400,31.0000,0.0,1.0,32.610,33.5900,30.9400,31.0000,101786600.0
2012-05-23,73600000.0,31.370,32.5000,31.3600,32.0000,0.0,1.0,31.370,32.5000,31.3600,32.0000,73600000.0
2012-05-24,50237200.0,32.950,33.2100,31.7700,33.0300,0.0,1.0,32.950,33.2100,31.7700,33.0300,50237200.0
2012-05-25,37149800.0,32.900,32.9500,31.1100,31.9100,0.0,1.0,32.900,32.9500,31.1100,31.9100,37149800.0
2012-05-29,78063400.0,31.480,31.6900,28.6500,28.8400,0.0,1.0,31.480,31.6900,28.6500,28.8400,78063400.0
2012-05-30,57267900.0,28.695,29.5500,27.8600,28.1900,0.0,1.0,28.695,29.5500,27.8600,28.1900,57267900.0
2012-05-31,111639200.0,28.545,29.6700,26.8300,29.6000,0.0,1.0,28.545,29.6700,26.8300,29.6000,111639200.0
2012-06-01,41855500.0,28.892,29.1500,27.3900,27.7200,0.0,1.0,28.892,29.1500,27.3900,27.7200,41855500.0
2012-06-04,35230300.0,27.200,27.6500,26.4400,26.9000,0.0,1.0,27.200,27.6500,26.4400,26.9000,35230300.0
2012-06-05,42473400.0,26.700,27.7600,25.7500,25.8690,0.0,1.0,26.700,27.7600,25.7500,25.8690,42473400.0
2012-06-06,61489200.0,26.070,27.1700,25.5200,26.8100,0.0,1.0,26.070,27.1700,25.5200,26.8100,61489200.0
2012-06-07,26159500.0,27.000,27.3500,26.1500,26.3100,0.0,1.0,27.000,27.3500,26.1500,26.3100,26159500.0
2012-06-08,38034000.0,26.550,27.7600,26.4400,27.1000,0.0,1.0,26.550,27.7600,26.4400,27.1000,38034000.0
2012-06-11,28219600.0,27.180,28.0700,26.8350,27.0050,0.0,1.0,27.180,28.0700,26.8350,27.0050,28219600.0
2012-06-12,15816800.0,27.480,27.7700,26.9600,27.4000,0.0,1.0,27.480,27.7700,26.9600,27.4000,15816800.0
2012-06-13,17102800.0,27.660,28.1000,27.1000,27.2700,0.0,1.0,27.660,28.1000,27.1000,27.2700,17102800.0
2012-06-14,16855000.0,27.650,28.3200,27.3800,28.2900,0.0,1.0,27.650,28.3200,27.3800,28.2900,16855000.0
2012-06-15,43563800.0,28.505,30.1000,28.3500,30.0140,0.0,1.0,28.505,30.1000,28.3500,30.0140,43563800.0
2012-06-18,42978900.0,29.955,32.0800,29.4100,31.4100,0.0,1.0,29.955,32.0800,29.4100,31.4100,42978900.0
2012-06-19,30849000.0,31.535,32.1800,30.7000,31.9110,0.0,1.0,31.535,32.1800,30.7000,31.9110,30849000.0
2012-06-20,15553600.0,31.920,31.9288,31.1500,31.6000,0.0,1.0,31.920,31.9288,31.1500,31.6000,15553600.0
2012-06-21,21875300.0,31.670,32.5000,31.5100,31.8400,0.0,1.0,31.670,32.5000,31.5100,31.8400,21875300.0
2012-06-22,74834000.0,32.410,33.4500,32.0600,33.0500,0.0,1.0,32.410,33.4500,32.0600,33.0500,74834000.0
2012-06-25,24352900.0,32.860,33.0200,31.5500,32.0600,0.0,1.0,32.860,33.0200,31.5500,32.0600,24352900.0
2012-06-26,24858700.0,32.690,33.4400,32.5000,33.1000,0.0,1.0,32.690,33.4400,32.5000,33.1000,24858700.0
2012-06-27,28568000.0,32.460,32.9000,31.9000,32.2300,0.0,1.0,32.460,32.9000,31.9000,32.2300,28568000.0
2012-06-28,17713300.0,31.960,32.1900,30.9000,31.3600,0.0,1.0,31.960,32.1900,30.9000,31.3600,17713300.0
2012-06-29,19526900.0,31.920,31.9900,30.7600,31.0950,0.0,1.0,31.920,31.9900,30.7600,31.0950,19526900.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-02-13,20880702.0,175.620,175.9700,173.1000,173.1500,0.0,1.0,175.620,175.9700,173.1000,173.1500,20880702.0
2018-02-14,27963758.0,173.450,179.8100,173.2119,179.5200,0.0,1.0,173.450,179.8100,173.2119,179.5200,27963758.0
2018-02-15,20554092.0,180.500,180.5000,176.8400,179.9600,0.0,1.0,180.500,180.5000,176.8400,179.9600,20554092.0
2018-02-16,20475445.0,178.990,179.8800,176.3000,177.3600,0.0,1.0,178.990,179.8800,176.3000,177.3600,20475445.0
2018-02-20,20887317.0,175.770,177.9500,175.1100,176.0100,0.0,1.0,175.770,177.9500,175.1100,176.0100,20887317.0
2018-02-21,22844006.0,176.710,181.2700,176.4000,177.9100,0.0,1.0,176.710,181.2700,176.4000,177.9100,22844006.0
2018-02-22,17085490.0,178.700,180.2100,177.4100,178.9900,0.0,1.0,178.700,180.2100,177.4100,178.9900,17085490.0
2018-02-23,18621950.0,179.900,183.3900,179.5100,183.2900,0.0,1.0,179.900,183.3900,179.5100,183.2900,18621950.0
2018-02-26,17418814.0,184.580,185.6600,183.2228,184.9300,0.0,1.0,184.580,185.6600,183.2228,184.9300,17418814.0
2018-02-27,15649326.0,184.450,184.7000,181.4600,181.4600,0.0,1.0,184.450,184.7000,181.4600,181.4600,15649326.0
2018-02-28,18208084.0,182.300,182.8800,178.1400,178.3200,0.0,1.0,182.300,182.8800,178.1400,178.3200,18208084.0
2018-03-01,23201626.0,179.010,180.1200,174.4100,175.9400,0.0,1.0,179.010,180.1200,174.4100,175.9400,23201626.0
2018-03-02,20025905.0,173.290,177.1100,172.9900,176.6200,0.0,1.0,173.290,177.1100,172.9900,176.6200,20025905.0
2018-03-05,16189280.0,176.200,181.1475,175.8900,180.4000,0.0,1.0,176.200,181.1475,175.8900,180.4000,16189280.0
2018-03-06,15086784.0,181.780,182.3800,179.1100,179.7800,0.0,1.0,181.780,182.3800,179.1100,179.7800,15086784.0
2018-03-07,19097293.0,178.740,183.8200,178.0700,183.7100,0.0,1.0,178.740,183.8200,178.0700,183.7100,19097293.0
2018-03-08,15336555.0,183.560,184.4000,181.4500,182.3400,0.0,1.0,183.560,184.4000,181.4500,182.3400,15336555.0
2018-03-09,17952177.0,183.910,185.5100,183.2100,185.2300,0.0,1.0,183.910,185.5100,183.2100,185.2300,17952177.0
2018-03-12,14873538.0,185.230,186.1000,184.2200,184.7600,0.0,1.0,185.230,186.1000,184.2200,184.7600,14873538.0
2018-03-13,17742312.0,185.610,185.9900,181.1100,181.8800,0.0,1.0,185.610,185.9900,181.1100,181.8800,17742312.0
2018-03-14,16426843.0,182.600,184.2500,181.8500,184.1900,0.0,1.0,182.600,184.2500,181.8500,184.1900,16426843.0
2018-03-15,15461869.0,183.240,184.0000,182.1900,183.8600,0.0,1.0,183.240,184.0000,182.1900,183.8600,15461869.0
2018-03-16,23090480.0,184.490,185.3300,183.4100,185.0900,0.0,1.0,184.490,185.3300,183.4100,185.0900,23090480.0
2018-03-19,86897749.0,177.010,177.1700,170.0600,172.5600,0.0,1.0,177.010,177.1700,170.0600,172.5600,86897749.0
2018-03-20,128925534.0,167.470,170.2000,161.9500,168.1500,0.0,1.0,167.470,170.2000,161.9500,168.1500,128925534.0
2018-03-21,105350867.0,164.800,173.4000,163.3000,169.3900,0.0,1.0,164.800,173.4000,163.3000,169.3900,105350867.0
2018-03-22,73389988.0,166.130,170.2700,163.7200,164.8900,0.0,1.0,166.130,170.2700,163.7200,164.8900,73389988.0
2018-03-23,52306891.0,165.440,167.1000,159.0200,159.3900,0.0,1.0,165.440,167.1000,159.0200,159.3900,52306891.0
2018-03-26,125438294.0,160.820,161.1000,149.0200,160.0600,0.0,1.0,160.820,161.1000,149.0200,160.0600,125438294.0
2018-03-27,76787884.0,156.310,162.8500,150.7500,152.1900,0.0,1.0,156.310,162.8500,150.7500,152.1900,76787884.0

In [ ]:
from sklearn.model_selection import train_test_split
X = 
# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, random_state=0)